import { Button, Input } from "antd";
import Head from "next/head"
import { useState } from "react";
import { colors } from "~/styles/constants";
import { api } from "~/utils/api"

const DocumentEditor = () => {
  const saveArticle = api.article.saveArticle.useMutation()
  const publishArticle = api.article.publishArticle.useMutation()

  const [articleTitle, setArticleTitle] = useState('')
  const [textAreaValue, setTextAreaValue] = useState('')

  const handleSaveArticle = async () => {
    try {
      const res = await saveArticle.mutateAsync({
        title: articleTitle,
        content: textAreaValue
      })

      console.log(res, 'successfully saved article')
    } catch (error) {
      console.log(error)
    }
  }

  const handlePublishArticle = async () => {
    try {
      const res = await publishArticle.mutateAsync({
        title: articleTitle,
        content: textAreaValue
      })

      console.log(res, 'successfully created article')
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <>
      <Head>
        <title>Bogey Blaine</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex-1 flex flex-col items-center p-3'>
        <div className='items-center flex justify-center cursor-pointer border-2 border-black font-bold text-xl w-[80%] h-48 mb-6'>
          Image +
        </div>
        <Input
          size='large'
          className='mx-auto w-[80%] mb-6'
          placeholder='The Title for this Article'
          value={articleTitle}
          onChange={(e) => setArticleTitle(e.target.value)}
        />
        <Input.TextArea 
          className='mx-auto w-[80%]'
          value={textAreaValue}
          onChange={(e) => setTextAreaValue(e.target.value)}
          autoSize={{ minRows: 10, maxRows: 20 }}
        />
        <SaveAndPublishButtons
          handleSaveArticle={handleSaveArticle}
          handlePublishArticle={handlePublishArticle}
        />
      </div>
    </>
  );
}

export default DocumentEditor

const SaveAndPublishButtons = ({ handleSaveArticle, handlePublishArticle }: { handleSaveArticle: () => Promise<void>, handlePublishArticle: () => Promise<void> }) => {
  return (
    <div className='flex gap-6 mt-9'>
      <Button
        size='large'
        className={`border-black hover:bg-black hover:text-white`}
        onClick={() => handleSaveArticle}
      >Save Article</Button>
      <Button
        size='large'
        style={{ background: colors.black}}
        className={`text-white`}
        onClick={() => handlePublishArticle}
      >Publish Article</Button>
    </div>
  )
}
