import Head from 'next/head'
import React, { useState } from 'react'
// Import the Slate editor factory.
import { createEditor } from 'slate'

// Import the Slate components and React plugin.
import { Slate, Editable, withReact } from 'slate-react'

const initialValue = [
  {
    type: 'paragraph',
    children: [{ text: 'Write a paragraph' }],
  },
]

const Editor = () => {
  const [editor] = useState(() => withReact(createEditor()))
  console.log(editor)

  return (
    <>
      <Head>
        <title>Bogey Blaine</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col gap-12 p-6">
        <div className='border-2 border-white h-[600px]'>
          <Slate editor={editor} value={initialValue}>
            <Editable
              onKeyDown={event => {
                console.log(event.key)
              }}
            />
          </Slate>
        </div>
      </main>
    </>
  )
}

export default Editor
